nicknames:
    -   id: 1
        nicknames:
        - ick
        - 星乃一歌
        - 星乃
        - 一歌
        - 一酱
        - ichika

    -   id: 2
        nicknames:
        - saki
        - 天馬咲希
        - 咲希
        - 天马咲希
        - 咲希
        - 溪

    -   id: 3
        nicknames:
        - hnm
        - 望月穂波
        - 望月
        - 穂波
        - 穗
        - honami
        - 萍

    -   id: 4
        nicknames:
        - shiho
        - 日野森志歩
        - 日野森志步
        - 志步
        - 志歩
        - 吸
        - 吸醬

    -   id: 5
        nicknames:
        - mnr
        - 花里みのり
        - 花里实乃里
        - 花里实乃理
        - 花里
        - 实乃里
        - 实乃理
        - みのり
        - 花花
        - minori

    -   id: 6
        nicknames:
        - hrk
        - 桐谷遥
        - 桐谷
        - 遥
        - 企鹅
        - haruka
        - 鹅

    -   id: 7
        nicknames:
        - airi
        - 桃井愛莉
        - 桃井爱莉
        - 桃井
        - 爱莉
        - 愛莉
        - 桃

    -   id: 8
        nicknames:
        - szk
        - 日野森雫
        - 雫
        - shizuku
        - 西子

    -   id: 9
        nicknames:
        - khn
        - 小豆沢こはね
        - 小豆沢心羽
        - 小豆沢
        - 心羽
        - こはね
        - kohane
        - 口哈捏
        - 仓鼠
        - 豆

    -   id: 10
        nicknames:
        - an
        - 白石杏
        - 白石
        - 杏
        - 安酱

    -   id: 11
        nicknames:
        - akt
        - 東雲彰人
        - 东云彰人
        - 彰人
        - 弟弟君
        - akito
        - 彰

    -   id: 12
        nicknames:
        - toya
        - 青柳冬弥
        - 青柳
        - 冬弥
        - 冬
        - 董秘

    -   id: 13
        nicknames:
        - tks
        - 天馬司
        - 天马司
        - 司
        - tms
        - 司马天
        - 大明星

    -   id: 14
        nicknames:
        - emu
        - 鳳えむ
        - 凤笑梦
        - 凤
        - 笑梦
        - 鳳
        - えむ
        - 冯笑梦
        - 姆

    -   id: 15
        nicknames:
        - nene
        - 草薙寧々
        - 草薙
        - 寧々
        - 寧
        - 草薙宁宁
        - 宁
        - 宁宁
        - 捏
        - 捏捏

    -   id: 16
        nicknames:
        - rui
        - 神代類
        - 神代类
        - 类
        - 類
        - sdl
        - 神代

    -   id: 17
        nicknames:
        - knd
        - 宵崎奏
        - 宵崎
        - 奏
        - 小气走
        - kanade
        - 走

    -   id: 18
        nicknames:
        - mfy
        - 朝比奈まふゆ
        - 朝比奈真冬
        - 朝比奈
        - 真冬
        - まふゆ
        - 雪
        - yuki
        - mafuyu
        - 马振东
        - 马

    -   id: 19
        nicknames:
        - ena
        - 東雲絵名
        - 东云绘名
        - 绘名
        - えな
        - enana
        - 董慧敏
        - 画

    -   id: 20
        nicknames:
        - mzk
        - 暁山瑞希
        - 晓山瑞希
        - 瑞希
        - 晓山
        - 暁山
        - mizuki
        - 糖
        - 肖瑞希
        - amia

    -   id: 21
        nicknames:
        - miku
        - 初音ミク
        - 初音未来
        - 初音
        - 未来
        - ミク
        - 葱
        - 初女士
        - 米库

    -   id: 22
        nicknames:
        - rin
        - 鏡音リン
        - 镜音铃
        - 镜音
        - 铃
        - リン
        - 橘

    -   id: 23
        nicknames:
        - len
        - 鏡音レン
        - 镜音连
        - 镜音
        - 连
        - レン
        - 蕉

    -   id: 24
        nicknames:
        - luka
        - 巡音ルカ
        - 巡音流歌
        - 巡音
        - 流歌
        - ルカ
        - 露卡
        - 鱼

    -   id: 25
        nicknames:
        - meiko
        - 大姐
        - MEIKO
        - 酒
        - mei

    -   id: 26
        nicknames:
        - kaito
        - 大哥
        - KAITO
        - 冰
        - kai
