disk-list:
    - mount-point: /
haruki-api:
    token: "xxx"
    suite-api:
        endpoint: "https://xxx"
        suite: "/public/{region}/suite/{user_id}"
        mysekai: "/public/{region}/mysekai/{user_id}"
        default-suite-keys: ['userCards', 'userDecks', 'userGamedata', 'userMusics', 'userMusicResults', 'userMysekaiMaterials','userAreas','userChallengeLiveSoloDecks','userCharacters','userMysekaiCanvases','userMysekaiFixtureGameCharacterPerformanceBonuses','userMysekaiGates','userWorldBloomSupportDecks','userHonors','userMysekaiCharacterTalks','userChallengeLiveSoloResults','userChallengeLiveSoloStages','userChallengeLiveSoloHighScoreRewards','userEvents','userWorldBlooms','userMusicAchievements','userPlayerFrames','userMaterials','upload_time']
        allow-regions: [ 'jp', '...' ]
    public-api:
        endpoint: "https://xxx"
        profile: "/api/{region}/{user_id}/profile"
        mysekai-photo: ""
        ranking-border: "/api/{region}/event/{event_id}/ranking-border"
        ranking-top100: "/api/{region}/event/{event_id}/ranking-top100"
        ranking-record-interval: 180
        allow-regions: [ 'jp', '...' ]
    music-alias: "https://xxx/alias/v1/music/{music_id}"
    timeout: 30
sekai-asset:
    default-timeout:
        masterdata-update-check: 30
        masterdata-download: 30
        asset-download: 60
    img-cache-max-res: 0
    sources:
        jp:
            materdata:
                haruki:
                    base-url: https://raw.githubusercontent.com/xxx/xxx-master/refs/heads/main/master
                    version-url: https://raw.githubusercontent.com/xxx/xxx-master/refs/heads/main/versions/current_version.json
            asset:
                haruki:
                    base-url: https://xxx/jp-assets
        cn: # ...
    ondemand-prefixes: ['event', 'gacha', 'music/long', 'mysekai', 'virtual_live']
    startapp-prefixes: ['bonds_honor', 'honor', 'thumbnail', 'character', 'music', 'rank_live', 'stamp', 'home/banner', 'player_frame', 'areaitem']
system:
    router-prefix: ""
    addr: 8888
    use-redis: false
    root: /home/xmlq/codes/gocodes
upload:
    path: uploads/file
    store-path: uploads/file
zap:
    level: info
    prefix: '[lunabot/xmlq/server]'
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    show-line: true
    log-in-console: true
    retention-day: -1
